### ISSUE TITLE
Which themes are supported?

### ISSUE THREAD

**Issue by slaFFik** [justintadlock/message-board#11]
After plugin activated I see this message:
```
The theme you are currently using does not support the Message Board plugin. Please activate a theme with support to continue enjoying full use of the plugin.
```

But I can't find anything related to know which themes are supported or what to do to make any theme work with this plugin.

**Comment by justintadlock** [comment]
No themes support the plugin yet.  We're still in the development phase.

But, themes declare support via `functions.php` like so:

	add_theme_support( 'message-board' );
