### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by Einkoro** [justintadlock/message-board#15]
Could you add composer support for installing the plugin? Quick sample composer.json:

```
{
    "name": "justintadlock/message-board",
    "description": "A simple WordPress forum plugin for us simple folks.",
    "type": "wordpress-plugin",
    "keywords": [
        "forum",
        "message board",
        "bulletin board",
        "wordpress"
    ],
    "homepage": "https://github.com/justintadlock/message-board",
    "license": "GPL-2.0",
    "authors": [
        {
            "name": "Justin Tadlock",
            "email": "justin@justintadlock.com"
        }
    ],
    "require": {
        "php": ">=5.6",
        "composer/installers": "~1.0"
    }
}
```

And register the package of the same name:
https://packagist.org/packages/submit

**Comment by michaelbeil** [comment]
You could fork the project, add a composer.json, and submit a Pull Request if you would like: https://github.com/justintadlock/message-board/pulls.

**Comment by Einkoro** [comment]
The package would still need to be registered by Justin on packagist and I'm not entirely sure if there is any additional information Justin would want in composer.json

**Comment by justintadlock** [comment]
I don't use Composer, but I'm always open to a PR.  Here's the one created for Hybrid Core, which would be a good starting point: https://github.com/justintadlock/hybrid-core/blob/master/composer.json

**Comment by Einkoro** [comment]
Is the project GPL2 or 2+? Might be a good idea to add the license to the repo.

I'll open a pull request for composer.json — will you register on packagist?

**Comment by justintadlock** [comment]
I'll register it.  The project is GPL 2+.

**Comment by Einkoro** [comment]
Any minimum PHP requirements? 5.4 is nearing EOL, 5.5+?

**Comment by justintadlock** [comment]
No requirements.

**Comment by michaelbeil** [comment]
@Einkoro are you still going to create a PR? Otherwise, I can help.

**Comment by justintadlock** [comment]
Everything should be done now.  It's on Packagist: https://packagist.org/packages/justintadlock/message-board

If it's working correctly for you, go ahead and close.

**Comment by Einkoro** [comment]
Thanks Justin.
