### ISSUE TITLE
create_forum_replies capability

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/message-board#4]
I think admin role should have `create_forum_replies` by default.

**Comment by justintadlock** [comment]
It should be the `create_replies` cap.  Are there still some places where the plugin is using `create_forum_replies`?  If we can find all those, I'll clear them up.

Caps still need a big overhaul.

**Comment by justintadlock** [comment]
That should be corrected in the last commit. Closing this one.  I'll reopen if we find another issue.
