### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/message-board#5]
In pagination I get URL like this: `board/topicspage/2`, not `board/topics/page/2` when using Post Name permalink setting. Here is relevant line.

https://github.com/justintadlock/message-board/blob/c35a17032e8cdbc3cb7fca974122cd00e53ed9ac/inc/common/template.php#L461

**Comment by justintadlock** [comment]
That one's hard to notice because I had my permalinks set up with a trailing slash.  It should be fixed in the above commit.

**Comment by samikeijonen** [comment]
That works.
