### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/message-board#7]
I tested the latest updates and I got this message: 

`Fatal error: Call to a member function get() on a non-object in D:\xampp\htdocs\foxnet-themes-shop\wp-includes\query.php on line 28`

**Comment by justintadlock** [comment]
The only time the plugin calls `$query->get()` is on forum search results.  You might have to reset your rewrite rules by visiting Settings > Permalinks in the admin.  Rewrite rules for search have changed.

**Comment by justintadlock** [comment]
Actually, I just realized that refers to `get_query_var()`.  I can't reproduce the issue, but we might have a call somewhere too early. Can you give me any more details?

**Comment by samikeijonen** [comment]
I only updated all the plugin files and got that error. I can try to check it out on clean install.

**Comment by justintadlock** [comment]
Any updates on this?

**Comment by samikeijonen** [comment]
It's working now.

**Comment by justintadlock** [comment]
Sounds good.  Maybe something got fixed in an update.
