### ISSUE TITLE
Fatal Error while changing forum category or parent forum

### ISSUE THREAD

**Issue by anandkumar** [justintadlock/message-board#8]
Hello Justin,

I have installed the [plugin](https://github.com/justintadlock/message-board/commit/b234a40c8dd8de9beb184e9fb7b784592eb24e2d) and created a few test forums then tried to rearrage them in sub forums.
**The message i got:**

    Notice: Undefined variable: wpdb in C:\xampp\htdocs\members\wp-content\plugins\message-board-master\inc\forum\functions.php on line 194
    Fatal error: Call to a member function prepare() on a non-object in C:\xampp\htdocs\members\wp-content\plugins\message-board-master\inc\forum\functions.php on line 194`

**How to replicate (potential) the issue:**
Try to move a forum from one category or parent forum to another using WP Dashboard. The transfer will be successful but will get above error.

**Comment by justintadlock** [comment]
That last commit should fix the error.

**Comment by anandkumar** [comment]
Yes, It's fine now. I will let you know anything else i found!
